spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  flyway:
    locations: classpath:db/migration
    enabled: true

server:
  servlet.context-path: /
  port: 8088

vaadin:
  async-supported: true
  load-on-startup: true
  allowed-packages: com.vaadin,org.vaadin

metadata:
  application-name: Cool Market
  minimal-age: 14
  support-email: makcum.kyp4ehkob@gmail.com
